login: &login
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost
  username: rails
  password: 

development: &default
  database: coderay_development
  <<: *login

test: &test
  database: coderay_test
  <<: *login

production: &production
  database: coderay_production
  <<: *login
